### ISSUE TITLE
Anchors on Our stories page

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#49]
Is it possible to add something (anchors) to this page /how-to-foster/our-stories so we can link (from another page) straight to the relevant section on this page? I would normally do this in a free text field but there aren't any on this page for me to edit.

So for example, on the events page, we have a line about 'our carers'. Ideally this would be a link taking users to the Our stories page (and so the carers stories appear at the top of the screen - /how-to-foster/our-stories.

**Comment by CharlesCarnell** [comment]
After having discussed this, the proposal add IDs to each section ( unfortunately these IDs will have to be vague due to the contents of each section, title included, being content-manageable ) and extend the buttonanchor functionality to include a trailing string for the internal anchors via asset IDs.

This will be a lot of work in Squiz, each metadata driven anchor's markup will need to be updated with a second conditional statement, metadata is going to need to be added in the case of every metadata driven anchor also.

I'm going to label this 'onhold' as something to return to after site launch.

**Comment by CharlesCarnell** [comment]
This was resolved in this context via WYSIWYG anchors having no related asset restrictions, however no functionality was developed for related asset metadata fields.
